import test from 'node:test';import assert from 'node:assert/strict';
import {freshState,deserialize,serialize} from '../src/state.js';
import {readHome,homeChoice,safeHomeDestination} from '../src/home.js';
import {plotStage,houseNeed} from '../src/readable-state.js';
const empty=()=>({...freshState(),plots:{},buildings:[],delights:[]});
test('optional corrupt home never discards paid world or camera',()=>{const s=freshState();s.home={version:1,kind:'house',anchor:'Infinity,0',baseY:0};const loaded=deserialize(serialize(s));assert.deepEqual(loaded.inventory,s.inventory);assert.deepEqual(loaded.plots,s.plots);assert.deepEqual(loaded.player,s.player);assert.equal(loaded.home,undefined);assert.equal(readHome({version:1,kind:'house',anchor:'0,0',baseY:-7.2}),null);});
test('return uses explicit candidate feet, dry support and a clear exit; failure is atomic',()=>{const s=empty(),before=serialize(s);const home=safeHomeDestination(s,{heightAt:()=>0});assert.equal(home.ok,true);assert.equal(home.feet,0);assert.equal(serialize(s),before);assert.equal(safeHomeDestination(s,{heightAt:()=>-7.2}).ok,false);assert.equal(safeHomeDestination(s,{heightAt:()=>0,obstacles:[{minX:-100,maxX:100,minZ:-100,maxZ:100,minY:0,maxY:5}]}).ok,false);assert.equal(serialize(s),before);});
test('home query avoids hole, head obstacle and chooses deterministic fallback',()=>{const s=empty();s.plots['0,5']={gx:0,gz:5,phase:'hole'};const env={heightAt:()=>0,obstacles:[{minX:-.5,maxX:.5,minZ:8.5,maxZ:9.5,minY:1.3,maxY:2}]};const a=safeHomeDestination(s,env);assert.equal(a.ok,true);assert.ok(Math.hypot(a.x,a.z-9)>.5);assert.deepEqual(a,safeHomeDestination(s,env));});
test('maturity overrides dry soil; positive water is growing',()=>{assert.equal(plotStage({phase:'filled',seed:'oak',growth:1,water:0}),'harvest');assert.equal(plotStage({phase:'filled',seed:'oak',growth:.5,water:.01}),'wet');assert.equal(plotStage({phase:'filled',seed:'oak',growth:.5,water:0}),'dry');});
test('sealed paid walls require replacement; missing roof retains base elevation',()=>{const parts=[{id:1,gx:0,gz:0,kind:'floor',level:0,rotation:0,baseY:0},...[0,1,2,3].map((rotation,i)=>({id:i+2,gx:0,gz:0,kind:'wall',rotation,level:0,baseY:0}))];assert.equal(houseNeed(parts,0,0).replace,true);parts[1].kind='door';const roof=houseNeed(parts.map(b=>({...b,baseY:-7.2})),0,0,-7.2);assert.equal(roof.kind,'roof');assert.ok(Math.abs(roof.y+4.8)<1e-8);});

test('removed home falls back explicitly while initial arrival adopts first land home once',()=>{const s=empty();s.home=homeChoice(s).record;assert.equal(s.home.chosen,false);s.buildings=[{id:1,kind:'roof',gx:0,gz:0,level:1,rotation:0,baseY:0},...[0,1,2,3].map((rotation,i)=>({id:i+2,kind:i===0?'door':'wall',gx:0,gz:0,level:0,rotation,baseY:0}))];s.home=homeChoice(s).record;assert.equal(s.home.kind,'house');s.buildings=[];s.home=homeChoice(s).record;assert.equal(s.home.kind,'arrival');assert.equal(s.home.chosen,true);assert.equal(homeChoice(s).home,null);});
